version: "3"
services:
  pserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 21025:21025
      - 21026:21026
    restart: always
    volumes:
      - /pserver/history
      - ./.screepsrc:/pserver/.screepsrc
      - ./mods/screepsmod-bots:/pserver/mods/screepsmod-bots
