version: "3"
services:
  pserver:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb
      - redis
    ports:
      - 21025:21025
      - 21026:21026
    restart: always

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017
    volumes:
      - /data/db
      - ./scripts/mongo/setup.js:/docker-entrypoint-initdb.d/setup.js

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - /data
