apiVersion: v1
kind: Service
metadata:
  name: pserver
  namespace: screeps
spec:
  ports:
  - name: "game"
    port: 21025
    targetPort: 21025
  - name: "cli"
    port: 21026
    targetPort: 21026
  selector:
    app: pserver
  type: LoadBalancer