apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pserver
  name: pserver
  namespace: screeps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pserver
  template:
    metadata:
      labels:
        app: pserver
    spec:
      containers:
      - name: pserver
        image: ${DOCKER_REPO}/screeps-pserver:${TAG_NAME}
        imagePullPolicy: ""
        volumeMounts:
        - name: screepsrc
          mountPath: /pserver/.screepsrc
          subPath: .screepsrc
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: screepsrc
          configMap:
            name: pserver-config
status: {}
