apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pserver
  name: pserver
  namespace: screeps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pserver
  template:
    metadata:
      labels:
        app: pserver
    spec:
      containers:
      - name: pserver
        image: ${DOCKER_REPO}/screeps-pserver:${TAG_NAME}
        imagePullPolicy: ""
        volumeMounts:
        - mountPath: /home/node/pserver/.screepsrc
          name: pserver-config
          subPath: .screepsrc
        - mountPath: /home/node/pserver/data
          name: pserver-db-json
      imagePullSecrets:
        - name: regcred
      volumes:
      - name: pserver-config
        configMap:
          name: pserver-config
status: {}
