apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pserver-redis
  name: pserver-redis
  namespace: screeps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pserver-redis
  template:
    metadata:
      labels:
        app: pserver-redis
    spec:
      containers:
      - name: pserver-redis
        image: redis:6.0-alpine
        imagePullPolicy: ""
